DROP DATABASE IF EXISTS BOOT;
DROP USER IF EXISTS 'BOOT'@'%';
CREATE DATABASE BOOT;
USE BOOT;
CREATE USER 'BOOT'@'%' IDENTIFIED BY 'BOOT';
GRANT ALL PRIVILEGES ON BOOT.* TO 'BOOT'@'%';
SHOW GRANTS FOR 'BOOT'@'%';