USE employee;

-- Q1
SELECT EMP_NAME, CONCAT(SUBSTRING(PHONE, 1, 3 ),'-', 
SUBSTRING(PHONE, 4, 4 ),'-', SUBSTRING(PHONE, 8, 4 )) AS PHONE
FROM employee
WHERE PHONE IS NOT NULL;

-- Q2
SELECT SUB.EMP_NAME AS 직원명,
CONCAT(SUBSTRING(HIRE_DATE, 1, 4), '년 ', SUBSTRING(HIRE_DATE, 6, 2), '월 ', SUBSTRING(HIRE_DATE, 9, 2), '일') AS 입사일,
FSALARY AS 급여
FROM (
	SELECT EMP_NAME, HIRE_DATE, SUBSTRING_INDEX(FORMAT(SALARY, 3), '.', 1) AS FSALARY
    FROM employee
    WHERE HIRE_DATE < '2004-1-1'
    ORDER BY HIRE_DATE, SALARY DESC) AS SUB;
    
-- Q3
SELECT EMP_NAME, SUBSTRING_INDEX(FORMAT(SALARY, 3), '.', 1) AS SALARY,
CONCAT(SUBSTRING_INDEX(BONUS * 100, '.', 1), '%')  AS BONUS,
FORMAT(SALARY + (SALARY * COALESCE(BONUS, 0)), 0) AS TOTAL_SALARY
FROM employee
ORDER BY CAST(TOTAL_SALARY AS SIGNED ) DESC;

-- Q4
SELECT EMP_NAME, EMAIL
FROM employee

-- Q5
