spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/drinkdb
    username: ohgiraffers
    password: ohgiraffers

  jpa:
    show-sql: true
    database: mysql
#    엔티티를 생성하면 db에 테이블이 바로 생성
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true